<?php
// $Id$

/**
 * @file
 * Provides the jQuery Tools "Tabs" javascript library and styles to the RE Context
 * Libraries module.
 */


// Constants:
define('RE_JQUERYTOOLS_TABS_MODULE_MACHINE_NAME', 're_jquerytools_tabs');
define('RE_JQUERYTOOLS_TABS_LIBRARY_MACHINE_NAME', 're_jquerytools_tabs');
define('RE_JQUERYTOOLS_TABS_LIBRARY_TITLE', 'jQuery Tools Tabs (provided by: re_jquerytools_tabs)');


/**
 * Implementation of hook_define_re_contextlibraries_library()
 */
function re_jquerytools_tabs_define_re_contextlibraries_library() {
  return array(RE_JQUERYTOOLS_TABS_MODULE_MACHINE_NAME . ':' . RE_JQUERYTOOLS_TABS_LIBRARY_MACHINE_NAME => t(RE_JQUERYTOOLS_TABS_LIBRARY_TITLE));
} // re_jquerytools_tabs_define_re_contextlibraries_library()


/**
 * Implements hook_library().
 *
 * Used to register libraries with the system.
 *
 * @todo Figure out why dependencies do NOT work here.
 */
function re_jquerytools_tabs_library() {
  $path_to_module = drupal_get_path('module', RE_JQUERYTOOLS_TABS_MODULE_MACHINE_NAME);
  $libraries[RE_JQUERYTOOLS_TABS_LIBRARY_MACHINE_NAME] = array(
    'title' => RE_JQUERYTOOLS_TABS_LIBRARY_TITLE, 
    'website' => 'http://flowplayer.org/tools/tabs/index.html', 
    'version' => '1.2.5', 
    'js' => array(
      $path_to_module .'/js/jquery.tools.min.js' => array(
        'group' => JS_LIBRARY,
        'weight' => 2,
      ),
      $path_to_module .'/js/re_jquerytools_tabs.js' => array(
        'group' => JS_LIBRARY,
        'weight' => 2,
      ),
    ),
    //'dependencies' => array('re_contextlibraries', 're_contextlibraries'),
  );
  return $libraries;
} // re_jquerytools_tabs_library()