<?php
// $Id$

/**
 * @file
 * Performs any 'first run' or 'last run' operations necessary for the module.
 * In this case, sets Drupal variables required to use the module on install,
 * removes them on uninstall.
 */


/**
 * Implements hook_install().
 */
function re_jquerycycle_install() {
  // Nothing to do!
} // re_jquerycycle_install()


/**
 * Implements hook_uninstall().
 */
function re_jquerycycle_uninstall() {
  // Nothing to do...
} // re_jquerycycle_uninstall()