<?php
// $Id$

/**
 * @file
 * Provides the jQuery Cycle javascript library and styles to the RE Context
 * Libraries module.
 */


// Constants:
define('RE_JQUERYCYCLE_MODULE_MACHINE_NAME', 're_jquerycycle');
define('RE_JQUERYCYCLE_LIBRARY_MACHINE_NAME', 're_jquerycycle');
define('RE_JQUERYCYCLE_LIBRARY_TITLE', 'jQuery Cycle (provided by: re_jquerycycle)');


/**
 * Implementation of hook_define_re_contextlibraries_library()
 */
function re_jquerycycle_define_re_contextlibraries_library() {
  return array(RE_JQUERYCYCLE_MODULE_MACHINE_NAME . ':' . RE_JQUERYCYCLE_LIBRARY_MACHINE_NAME => t(RE_JQUERYCYCLE_LIBRARY_TITLE));
} // re_jquerycycle_define_re_contextlibraries_library()


/**
 * Implements hook_library().
 *
 * Used to register libraries with the system.
 *
 * @todo Figure out why dependencies do NOT work here.
 */
function re_jquerycycle_library() {
  $path_to_module = drupal_get_path('module', RE_JQUERYCYCLE_MODULE_MACHINE_NAME);
  $libraries[RE_JQUERYCYCLE_LIBRARY_MACHINE_NAME] = array(
    'title' => RE_JQUERYCYCLE_LIBRARY_TITLE, 
    'website' => 'http://malsup.com/jquery/cycle/', 
    'version' => '2.99', 
    'js' => array(
      $path_to_module . '/js/jquery.easing.1.3.js' => array(
        'group' => JS_LIBRARY,
        'weight' => 2,
      ),
      $path_to_module . '/js/jquery.cycle/jquery.cycle.all.min.js' => array(
        'group' => JS_LIBRARY,
        'weight' => 4,
      ),
      $path_to_module . '/js/re_jquerycycle.js' => array(
        'group' => JS_LIBRARY,
        'weight' => 6,
      ), 
      array(
        'type' => 'setting',
        'data' => array(
            're_jquerycycle' => array(
              'fit' => True,
              'fx' => 'scrollVert',
              'height' => 400,
              'next' => '.re_slideshow-next',
              'pager' => '#re-slideshow-view-display-id-block-navigation',
              'prev' => '.re_slideshow-prev',   
            ), 
        ),
      ),  
    ),
    //'dependencies' => array('re_contextlibraries', 're_contextlibraries'),
  );
  return $libraries;
} // re_jquerycycle_library()
