<?php
// $Id$

/**
 * @file
 * Provides the Flowplayer javascript library and styles to the RE Context
 * Libraries module.
 */


/**
 * Implementation of hook_define_re_contextlibraries_library().
 */
function re_flowplayer_define_re_contextlibraries_library() {
  $path_to_module = drupal_get_path('module', 're_flowplayer');
  $library = array(
    're_flowplayer' => array(
      'name' => 'Flowplayer (provided by: re_flowplayer)',
      'js' => array(
        $path_to_module .'/js/flowplayer/example/flowplayer-3.2.6.min.js',
        $path_to_module .'/js/re_flowplayer.js',
        array(
          're_flowplayer' => array(
            'pathToModule' => $path_to_module,
          ),
        ),
      ),
      'css' => array(
        $path_to_module .'/css/re_flowplayer.css',
      ),
    ),
  );
  return $library;
} // re_flowplayer_define_re_contextlibraries_library()