<?php
// $Id$

/**
 * @file
 * Provides the Flowplayer javascript library and styles to the RE Context
 * Libraries module.
 */


// Constants:
define('RE_FLOWPLAYER_MODULE_MACHINE_NAME', 're_flowplayer');
define('RE_FLOWPLAYER_LIBRARY_MACHINE_NAME', 're_flowplayer');
define('RE_FLOWPLAYER_LIBRARY_TITLE', 'Flowplayer video player (provided by: re_flowplayer)');


/**
 * Implementation of hook_define_re_contextlibraries_library()
 */
function re_flowplayer_define_re_contextlibraries_library() {
  return array(RE_FLOWPLAYER_MODULE_MACHINE_NAME . ':' . RE_FLOWPLAYER_LIBRARY_MACHINE_NAME => t(RE_FLOWPLAYER_LIBRARY_TITLE));
} // re_flowplayer_define_re_contextlibraries_library()


/**
 * Implements hook_library().
 *
 * Used to register libraries with the system.
 *
 * @todo Figure out why dependencies do NOT work here.
 */
function re_flowplayer_library() {
  $path_to_module = drupal_get_path('module', RE_FLOWPLAYER_MODULE_MACHINE_NAME);
  $libraries[RE_FLOWPLAYER_LIBRARY_MACHINE_NAME] = array(
    'title' => RE_FLOWPLAYER_LIBRARY_TITLE, 
    'website' => 'http://flowplayer.org/', 
    'version' => '3.2.6', 
    'js' => array(
      $path_to_module .'/js/flowplayer/example/flowplayer-3.2.6.min.js' => array(
        'group' => JS_LIBRARY,
        'weight' => 2,
      ),
      $path_to_module .'/js/re_flowplayer.js' => array(
        'group' => JS_LIBRARY,
        'weight' => 1,
      ),
      array(
        'type' => 'setting', 
        'data' => array(
          're_flowplayer' => array(
            'pathToModule' => $path_to_module
          ),
        ),
      ),
    ),
    //'dependencies' => array('re_contextlibraries', 're_contextlibraries'),
  );
  return $libraries;
} // re_flowplayer_library()